### ISSUE TITLE
Typescript run time errors with jwt dependency

### ISSUE THREAD

**Issue by garrettbsettles** [PacktPublishing/Deno-Web-Development#5]
Hi there,

If you open https://github.com/PacktPublishing/Deno-Web-Development/blob/master/Chapter06/sections/3-adding-authorization/museums-api/src/index.ts and run `deno run -A index.ts` or  `deno run -A --unstable index.ts`, the following errors are thrown

```
error: TS2345 [ERROR]: Argument of type '"jwk"' is not assignable to parameter of type '"raw"'.
    "jwk",
    ~~~~~
    at https://deno.land/x/god_crypto@v1.4.6/src/rsa/rsa_wc.ts:55:5

TS2345 [ERROR]: Argument of type '"jwk"' is not assignable to parameter of type '"raw"'.
    "jwk",
    ~~~~~
    at https://deno.land/x/god_crypto@v1.4.8/src/rsa/rsa_wc.ts:55:5

TS2345 [ERROR]: Argument of type '"jwk"' is not assignable to parameter of type '"raw"'.
        "jwk",
        ~~~~~
    at https://deno.land/x/god_crypto@v1.4.8/src/aes/aes_wc.ts:25:9

Found 3 errors.
```

**Comment by garrettbsettles** [comment]
Looks like it is related to this issue - https://github.com/invisal/god_crypto/issues/39

**Comment by garrettbsettles** [comment]
Nevermind, downgraded Deno to 1.7.5 using `deno upgrade --version 1.7.5` and everything works again - wonder why it doesn't work on the latest version
